spring:
  application:
    name: notes-app-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
            ${OAUTH2_ISSUER_URI}

cors:
  config:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:*}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}
